// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlueC2BPGh50et892hc17RtqyT4q4JxFk',
    appId: '1:729857640359:web:f0e372cb85813ac4d75882',
    messagingSenderId: '729857640359',
    projectId: 'dole-qr-attendance-system',
    authDomain: 'dole-qr-attendance-system.firebaseapp.com',
    storageBucket: 'dole-qr-attendance-system.appspot.com',
    measurementId: 'G-LPCTNHSV6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVbYnjKLDLo-wqafERlVmfoIW40Vs4JyI',
    appId: '1:729857640359:android:e05d058528b73c7bd75882',
    messagingSenderId: '729857640359',
    projectId: 'dole-qr-attendance-system',
    storageBucket: 'dole-qr-attendance-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-VTOvCc37GwnJ8XsdlEhucN1nn6sObks',
    appId: '1:729857640359:ios:0c5128759fe0ede5d75882',
    messagingSenderId: '729857640359',
    projectId: 'dole-qr-attendance-system',
    storageBucket: 'dole-qr-attendance-system.appspot.com',
    iosClientId:
        '729857640359-748c324ft2b3mlavsvrs845lbdgf6ano.apps.googleusercontent.com',
    iosBundleId: 'com.example.doleAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-VTOvCc37GwnJ8XsdlEhucN1nn6sObks',
    appId: '1:729857640359:ios:6d486c06ee4f6f64d75882',
    messagingSenderId: '729857640359',
    projectId: 'dole-qr-attendance-system',
    storageBucket: 'dole-qr-attendance-system.appspot.com',
    iosClientId:
        '729857640359-v1gpcdb9g644trmt2ifq297sce0apa1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.doleAttendance.RunnerTests',
  );
}
